name: build-and-publish-image

on:
  push:
    tags: [ '*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit -1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get variables
        id: variables
        run: |
          COLLECTOR_VERSION=$(jq -r .args.COLLECTOR_VERSION build.json)
          echo "::set-output name=COLLECTOR_VERSION::$COLLECTOR_VERSION"
          SERVER_VERSION=$(jq -r .args.SERVER_VERSION build.json)
          echo "::set-output name=SERVER_VERSION::$SERVER_VERSION"
          BUILD_FROM=$(jq -r .build_from.amd64 build.json)
          echo "::set-output name=BUILD_FROM::$BUILD_FROM"
          ARCH_TAG=$(echo "${{matrix.arch}}" | tr -d "linux" | tr -d "/")
          echo "::set-output name=ARCH_TAG::$ARCH_TAG"


      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.arch }}
          build-args: |
            BUILD_FROM=${{ steps.variables.outputs.BUILD_FROM }}
            COLLECTOR_VERSION=${{ steps.variables.outputs.COLLECTOR_VERSION }}
            SERVER_VERSION=${{ steps.variables.outputs.SERVER_VERSION }}
            BROTLI_SUPPORT=0
          file: ./Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ steps.variables.outputs.ARCH_TAG }}:${{ github.ref_name }}


